### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by nSahne** [PeanutI3utter/TUDA-Rate#6]
I'd like to inquire about the state of this project and at the same time propose to extend the scope of this project. 
Why limit reviews to TU Darmstadt only? There is no viable rating system for lectures/professors in Germany that I'm aware of. The website meinprof.de is the only one that comes to mind, and it sucks/got into legal trouble. 
Thank you for your attention and I'd love to hear your opinions on this!

**Comment by julieeecious** [comment]
Hey there, thank you for reaching out, and we would definitely take your proposal into consideration. We have put the project temporarily on hold due to the university study, we will continue working on it approximately from the end of September.

**Comment by nSahne** [comment]
Hey there, thank you for your reply and your consideration! I will keep an eye on this project and reach out again in September. I would love to contribute on this, as a review system is sorely missing from my studies as well.

**Comment by julieeecious** [comment]
We are slowly ramping up the progress. You can join our whatsapp group and share your idea: https://chat.whatsapp.com/CamxbIeAWvH8OVX73muHT8
